### ISSUE TITLE
@fortawesome/react-fontawesome make frontend node_modules unable to install

### ISSUE THREAD

**Issue by arnaudmanaranche** [lambda2/luua#10]
**Describe the bug**
When running the `yarn` command, it throws an error:

```
➜ yarn
yarn install v1.22.0
[1/4] 🔍  Resolving packages...
[2/4] 🚚  Fetching packages...
error An unexpected error occurred: "https://npm.fontawesome.com/@fortawesome/react-fontawesome/-/0.1.9/react-fontawesome-0.1.9.tgz: Request failed \"401 Unauthorized\"".
```

**To Reproduce**
1. Navigate to the `frontend` folder
2. Run the `yarn`command
3. See error

**Desktop (please complete the following information):**
 - OS: [e.g. macOS Catalina 10.15.3]

**Comment by lambda2** [comment]
Hey @arnaudmanaranche, we're using font-awesome pro, and that's indeed a problem for open sourcing this as you'll need a npm private token.
I'll try to switch to font-awesome free as soon as I can !

**Comment by lambda2** [comment]
Should be good now 👌
